### ISSUE TITLE
[issue] Timeline drops to live, when using playback

### ISSUE THREAD

**Issue by zubenco** [koush/nvr.scrypted.app#13]
If I switching to yesterday or any date and using the timeline, the timeline always drops to the live.

Always when I need to see and download some from archive (playback) it's always impossible for me.

https://user-images.githubusercontent.com/111895113/236295069-e0e4a4e2-e416-46ba-bdf0-c346ef321226.MOV

**Comment by koush** [comment]
oh weird, will see if I can repro that here.

**Comment by koush** [comment]
this was fixed with the recent timestamp fixes
