### ISSUE TITLE
Feature Request: Archival Ability

### ISSUE THREAD

**Issue by omayhemo** [koush/nvr.scrypted.app#20]
I'd like to keep X number of days on my local drive and archive to NAS for the remainder.  While I can mount a NAS drive and use it successfully in the NVR, it's pretty slow and sometimes unresponsive in the app.  It'd be great to enable a feature that allows you to set a variable number of days to retain locally and then offload the remainder to archive and still be able to view both in the app.

**Comment by koush** [comment]
I'd use rsync or something. The nvr file storage is immutable and file based and so it lends itself well to replication via tools like rsync.

**Comment by koush** [comment]
Offloading is also an expensive operation. it's basically continual write to a NAS anyways for a rolling NVR.

**Comment by omayhemo** [comment]
I want to retain access to the snapshots, clips and recordings in nvr.scrypted while storing them in an alternative location for longer archival.  Am I missing how this would work with such a configuration?
