### ISSUE TITLE
Large available free storage isn't recognised above a certain level

### ISSUE THREAD

**Issue by douginoz** [koush/nvr.scrypted.app#21]
I've got a 150TB drive array that has 5-10TB free on it.  If I try to point the nvr to it, it thinks there isn't any free space and starts deleting files.  As a workaround I plugged in a USB hard drive but I can't keep that in there any longer and need to use the array.

(This is already a known problem, I'm just assigning an issue so it gets tracked)

**Comment by koush** [comment]
Fixed in upcoming plugin release. Thanks for the report.

**Comment by YG-Thalys** [comment]
Same issue here, I have 2.5 TB free but my array is 30 TB so it doesn't want to record anymore and it deleted all recordings because it's lower than 10%. It would be great to just have a setting somewhere to define the percentage ourselves :)

**Comment by koush** [comment]
The fix is in the beta plugin (check plugin dropdown).

**Comment by koush** [comment]
I'll release to stable after I finish up some work on the beta plugin. It's functionally stable, but a detection quality decrease need to be resolved first.

**Comment by koush** [comment]
Fixed. If several tb is free, the low watermark is ignored.
