### ISSUE TITLE
Separate expiration for constant recording from events

### ISSUE THREAD

**Issue by pashdown** [koush/nvr.scrypted.app#23]
Thinking about deploying this in a commercial setting with a requirement for retention of events.  Having separate expiration on the constant recording from the events recordings would be nice, as we are required to keep a year's worth of events.  Constant recording storage for a year would be prohibitive.

**Comment by 0dragosh** [comment]
I would also really like this feature, separate retention for events/fulltime recordings, and also separate retention per cameras would be nice.

**Comment by koush** [comment]
the low and remote streams are now on separate drives.
