### ISSUE TITLE
Feature Request: More retention options

### ISSUE THREAD

**Issue by linedpaper** [koush/nvr.scrypted.app#26]
Ideally I would like to be able to retain detection events for a longer time period than continuous recording.  Also, the ability to set a max size on the storage manually would be nice.  Setting a quota on the share in my NAS doesn't change the amount of storage perceived as available and I would rather it not be an entirely separate volume, I would prefer to set a max of say 2tb, then use the retention option to automatically overwrite once it hits the threshold.

**Comment by koush** [comment]
There's no plans to set max storage. Create a partition or use retention days. Determining storage usage per directory is an extremely expensive operation.

**Comment by linedpaper** [comment]
If not a max option, then different retention for events.  Other NVR apps already have these features so both are very doable.  A partition just for NVR is a poor workaround and retention days does not account for max size.

**Comment by koush** [comment]
You can work backwards and determine how many days is equal to the number of terabytes you want.

Other products make different design decisions and have different goals, and poorly planned feature parity can have adverse effects.

Run

`time du -h /path/to/nvr/storage` and tell me how long it takes. And try to scrub the timeline a few days back while it is doing that.

**Comment by koush** [comment]
Event backup can likely be a separate plugin or option, but is not currently on the horizon.

**Comment by koush** [comment]
did some research on how other solutions implement max size, and they maintain a database of files (due to recursive file enumeration being slow) and then computing it that way. Problem is database gets out of sync. I think retention days or partition size is the correct solution here.
