### ISSUE TITLE
Feature Request: Separated Storages / retention times per camera / stream

### ISSUE THREAD

**Issue by btk999** [koush/nvr.scrypted.app#3]
Hi,

it would be very nice to be able to set individual storages  and retention timesper camera and stream.

High resolution streams could be stored on a big but slowHDD, low resolution streams (for scrubbing/scrolling in the nvr timeline)  could be stored on a small  but fast ssd so.
That might be helpful to increase the access times while scrolling to the timeline - i observed some lags / delays on reading the low resolution streams (which i think is normal for a HDD that has to handle constant writes with 10mb/s (10x 4k cameras).

Also it would be nice to set longer retention times on more relevant cameras in a setup.
It could even make sense to set longer retention times for recordings with motion events (e.g. keep everything with motion 30 days, everything without motion deleted after 10 days).

Maybe its even possible to implement a kind of "archiving" mode - so that at first everything is written to a SSD storage and after some days everything (or just the recordings without motion events) is moved to a different storage (HDD).

Just some thoughts :)

**Comment by btk999** [comment]
i found a workaroudn for me for the most important topic (recordlow res streams on ssd, high res streams on HDD)
On Windows i created softlinks (mklink /D ; not symbolic links) which redirects the streams to a hdd.
![image](https://user-images.githubusercontent.com/20415739/227922633-b97edd55-f6fb-40c2-915b-b411b3073a13.png)

i get an error on the nvr plugin startup (mkdir failed) but recording / playback works fine.

**Comment by koush** [comment]
> i found a workaround for me for the most important topic (record low res streams on ssd, high res streams on HDD)

Yep, this is exactly what I want to make possible. Closing this issue as duplicate, as we're discussing this as an exact improvement in another issue.

**Comment by koush** [comment]
https://github.com/koush/nvr.scrypted.app/issues/4
