### ISSUE TITLE
Feature Request - Modify Notification Title and Body

### ISSUE THREAD

**Issue by SirBigBits** [koush/nvr.scrypted.app#7]
Would like the ability to modify and/or remove the **Notification Title** and **Notification Body** for Scrypted NVR iOS Device notifications.

**Comment by gagy2** [comment]
+1 would like the option to modify / Rename to add French notifications

**Comment by koush** [comment]
Can you provide examples of what you want, so I can build something appropriate?

**Comment by SirBigBits** [comment]
Hey, thanks for considering my feature request. 

I really just want the ability to remove or change the Title and Subject on notifications. I can tell by the thumbnails what camera it is, and what’s being detected, so cleaning up the notifications is all I’m looking to do. If it can’t be done,  no worries. I’m liking Scrypted more and more every day. You’re doing a fantastic job with it. 

![image](https://github.com/koush/nvr.scrypted.app/assets/129541321/071804bb-d0e8-48f1-8b4e-d1d0d6734adb)

**Comment by koush** [comment]
Can you edit/markup that image so I know exactly what you are expecting? I need a couple concrete use cases so I can implement this correctly for everyone.

**Comment by SirBigBits** [comment]
Sure, give me moment.

**Comment by SirBigBits** [comment]
![image](https://github.com/koush/nvr.scrypted.app/assets/129541321/d4b2398f-5733-4c8d-baf0-b706916b2381)

**Comment by SirBigBits** [comment]
![image](https://github.com/koush/nvr.scrypted.app/assets/129541321/f47fc73f-6d2f-4928-8f61-0516b2a065ea)

**Comment by SirBigBits** [comment]
If you plan on working on having a gif animation in notifications, spend your time on that if anything. :)

**Comment by gagy2** [comment]
Here is a screen shot on how it was done in Blueiris.. might help, 
We had the option to use variable and enter text so possible to enter in the language of choice or to remove entirely
![image](https://github.com/koush/nvr.scrypted.app/assets/23300694/b87bcc21-3ad3-48f1-a555-b3cb81671c24)

**Comment by koush** [comment]
Can be done with a script. https://discord.com/channels/882329362295316500/933126942943739956/1142115455033688114
